# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgot_passUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_forgotPass(object):
    def setupUi(self, forgotPass):
        forgotPass.setObjectName("forgotPass")
        forgotPass.resize(400, 300)

        self.mobile_num_text_2 = QtWidgets.QLineEdit(forgotPass)
        self.mobile_num_text_2.setGeometry(QtCore.QRect(120, 50, 171, 31))
        self.mobile_num_text_2.setMaximumSize(QtCore.QSize(16777215, 16777201))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.mobile_num_text_2.setFont(font)
        self.mobile_num_text_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.mobile_num_text_2.setText("")
        self.mobile_num_text_2.setObjectName("mobile_num_text_2")
        self.submit_button = QtWidgets.QPushButton(forgotPass)
        self.submit_button.setGeometry(QtCore.QRect(160, 160, 75, 23))
        self.submit_button.setObjectName("submit_button")
        self.otp_text = QtWidgets.QLineEdit(forgotPass)
        self.otp_text.setGeometry(QtCore.QRect(130, 120, 131, 31))
        self.otp_text.setMaximumSize(QtCore.QSize(16777215, 16777201))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.otp_text.setFont(font)
        self.otp_text.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.otp_text.setText("")
        self.otp_text.setObjectName("otp_text")
        self.send = QtWidgets.QPushButton(forgotPass)
        self.send.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.send.setAutoDefault(False)
        self.send.setDefault(False)
        self.send.setFlat(False)
        self.send.setObjectName("send")

        self.retranslateUi(forgotPass)
        QtCore.QMetaObject.connectSlotsByName(forgotPass)

    def retranslateUi(self, forgotPass):
        _translate = QtCore.QCoreApplication.translate
        forgotPass.setWindowTitle(_translate("forgotPass", "Form"))
        self.mobile_num_text_2.setPlaceholderText(_translate("forgotPass", "enter mob num here"))
        self.submit_button.setText(_translate("forgotPass", "Submit"))
        self.otp_text.setPlaceholderText(_translate("forgotPass", "enter otp here"))
        self.send.setText(_translate("forgotPass", "send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    forgotPass = QtWidgets.QWidget()
    ui = Ui_forgotPass()
    ui.setupUi(forgotPass)
    forgotPass.show()
    sys.exit(app.exec_())
