# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Message.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Massege_box(object):
    def setupUi(self, Massege_box):
        Massege_box.setObjectName("Massege_box")
        Massege_box.resize(259, 68)
        self.gridLayout = QtWidgets.QGridLayout(Massege_box)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(Massege_box)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Massege_box)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Massege_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton.clicked.connect(Massege_box.close)

        self.retranslateUi(Massege_box)
        QtCore.QMetaObject.connectSlotsByName(Massege_box)

    def retranslateUi(self, Massege_box):
        _translate = QtCore.QCoreApplication.translate
        Massege_box.setWindowTitle(_translate("Massege_box", "Successfull"))
        self.pushButton.setText(_translate("Massege_box", "done"))
        self.label.setText(_translate("Massege_box", "Successfully Loggedin"))
        self.label_2.setText(_translate("Massege_box", "Say Parrot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Massege_box = QtWidgets.QDialog()
    ui = Ui_Massege_box()
    ui.setupUi(Massege_box)
    Massege_box.show()
    sys.exit(app.exec_())
