# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_passUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_pass(object):
    def setupUi(self, new_pass):
        new_pass.setObjectName("new_pass")
        new_pass.resize(400, 300)
        self.new_password = QtWidgets.QLineEdit(new_pass)
        self.new_password.setGeometry(QtCore.QRect(100, 120, 201, 31))
        self.new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_password.setObjectName("new_password")
        self.conferm_new_password = QtWidgets.QLineEdit(new_pass)
        self.conferm_new_password.setGeometry(QtCore.QRect(100, 160, 201, 31))
        self.conferm_new_password.setText("")
        self.conferm_new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.conferm_new_password.setObjectName("conferm_new_password")
        self.submit_button = QtWidgets.QPushButton(new_pass)
        self.submit_button.setGeometry(QtCore.QRect(160, 200, 75, 23))
        self.submit_button.setObjectName("submit_button")
        self.email_text = QtWidgets.QLineEdit(new_pass)
        self.email_text.setGeometry(QtCore.QRect(100, 90, 201, 21))
        self.email_text.setObjectName("email_text")

        self.retranslateUi(new_pass)
        QtCore.QMetaObject.connectSlotsByName(new_pass)

    def retranslateUi(self, new_pass):
        _translate = QtCore.QCoreApplication.translate
        new_pass.setWindowTitle(_translate("new_pass", "Form"))
        self.new_password.setPlaceholderText(_translate("new_pass", "new password"))
        self.conferm_new_password.setPlaceholderText(_translate("new_pass", "Confirm password"))
        self.submit_button.setText(_translate("new_pass", "Submit"))
        self.email_text.setPlaceholderText(_translate("new_pass", "enter your email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_pass = QtWidgets.QWidget()
    ui = Ui_new_pass()
    ui.setupUi(new_pass)
    new_pass.show()
    sys.exit(app.exec_())
